#include<gl/glew.h>
#include<gl/freeglut.h>
#include<glm/glm/glm.hpp>
#include<glm/glm/ext.hpp>
#include<glm/glm/gtc/matrix_transform.hpp>
#include<iostream>
#include<random>
#include<vector>
#include<utility>
#include"filetobuf.h"
#include"ShaderFunc.h"
#include"Camera.h"
#include"Player.h"
#include"Light.h"
#include"Projection.h"
#include"Bullet.h"//weapon
#include"Pistol.h"//Gun
#include"Rifle.h"
#include"Sniper.h"
#include"Enum.h"
#include"Map.h"//map
#include"stair.h"
#include"Wall.h"
#include"Enemy.h"
#include"FlyRobotManager.h"
#include"GameSound.h"
#include"Crash.h"
//#include"Robot.h"
#include"Boss.h"
//#include"Random.h"
#define STB_IMAGE_IMPLEMENTATION
#include"stb_image.h"
#include"CrossHead.h"
#include"ParticleManager.h"
#include"Random.h"
#include"RobotManager.h"